// ============================================================
// File    : ADS1247_DRIVE.v
// Purpose : Optimized ADS1247 driver, RDATAC continuous read mode
// Target  : i_sys_clk = 100MHz, o_adc_sclk = 500kHz
//
// Main changes vs old version:
//   1. o_adc_sclk is generated by divider, not directly from i_sys_clk.
//   2. SPI TX/RX only changes on generated SCLK edges.
//   3. ADS1247 24-bit data is treated as signed two's-complement.
//   4. Sample-sum window defaults to 10 samples, keeping 5SPS -> 2s update.
//   5. DRDY event is latched by falling edge to avoid repeated same-frame read.
//   6. First DISCARD_NUM samples after init are discarded.
//   7. Sends RDATAC(0x14) once after register initialization; reads 24 bits after each DRDY.
//   8. Key internal signals are marked for PAP debug/ILA.
//
// SPI mode:
//   CPOL = 0
//   ADS1247 latches DIN on SCLK falling edge.
//   ADS1247 updates DOUT on SCLK rising edge.
//   FPGA updates SDI on the rising edge after each sampled bit.
//   FPGA samples SDO on SCLK falling edge.
//
// Read mode:
//   Continuous read mode. After register initialization, FPGA sends RDATAC(0x14) once.
//   Then, after each DRDY falling edge, FPGA directly clocks 24 bits.
//   No RDATA(0x12) is sent during normal read.
// ============================================================

module ADS1247_DRIVE #(
    parameter integer SYS_CLK_HZ         = 100_000_000,
    parameter integer SCLK_HZ            = 500_000,

    // 10ms @100MHz = 1_000_000 cycles
    parameter integer GPIO_PULSE_CYCLES  = 1_000_000,

    // 1s @100MHz = 100_000_000 cycles
    parameter integer ADC_TIMEOUT_CYCLES = 100_000_000,

    // ADC reset/start settle delay before register configuration.
    // 10ms @100MHz = 1_000_000 cycles
    parameter integer RESET_DELAY_CYCLES = 1_000_000,

    // CS setup/hold delay.
    // 4us @100MHz = 400 cycles
    parameter integer CS_DELAY_CYCLES    = 400,

    // Sum 10 samples. With ADS1247 5SPS, output updates every 2s.
    parameter integer AVG_NUM            = 10,

    // Discard first few samples after register initialization.
    parameter integer DISCARD_NUM        = 3
)(
    input                           i_sys_clk,      /* synthesis PAP_MARK_DEBUG = "1" */
    input                           i_sys_rst_n,

    input                           i_read_clk,     /* synthesis PAP_MARK_DEBUG = "1" */ // reserved, not used in this version
    output [31:0]      o_read_data,    /* synthesis PAP_MARK_DEBUG = "1" */

    output                          o_adc_sclk,     /* synthesis PAP_MARK_DEBUG = "1" */
    output reg                      o_adc_cs_n,     /* synthesis PAP_MARK_DEBUG = "1" */
    output                          o_adc_sdi,      /* synthesis PAP_MARK_DEBUG = "1" */
    input                           i_adc_drdy,     /* synthesis PAP_MARK_DEBUG = "1" */
    input                           i_adc_sdo,      /* synthesis PAP_MARK_DEBUG = "1" */
    output                          o_adc_start,    /* synthesis PAP_MARK_DEBUG = "1" */
    output                          o_adc_reset,    /* synthesis PAP_MARK_DEBUG = "1" */

    output wire                     o_gpio_master_data /* synthesis PAP_MARK_DEBUG = "1" */
);

// ============================================================
// Local parameters
// ============================================================

localparam integer SCLK_HALF_PERIOD_RAW    = SYS_CLK_HZ / (SCLK_HZ * 2);
localparam integer SCLK_HALF_PERIOD_CYCLES = (SCLK_HALF_PERIOD_RAW > 0) ? SCLK_HALF_PERIOD_RAW : 1;
localparam integer GPIO_PULSE_CYCLES_EFF   = (GPIO_PULSE_CYCLES  > 0) ? GPIO_PULSE_CYCLES  : 1;
localparam integer ADC_TIMEOUT_CYCLES_EFF  = (ADC_TIMEOUT_CYCLES > 0) ? ADC_TIMEOUT_CYCLES : 1;
localparam integer RESET_DELAY_CYCLES_EFF  = (RESET_DELAY_CYCLES > 0) ? RESET_DELAY_CYCLES : 1;
localparam integer CS_DELAY_CYCLES_EFF     = (CS_DELAY_CYCLES    > 0) ? CS_DELAY_CYCLES    : 1;
localparam integer AVG_NUM_EFF             = (AVG_NUM            > 0) ? AVG_NUM            : 1;
localparam integer DISCARD_NUM_EFF         = (DISCARD_NUM        > 0) ? DISCARD_NUM        : 0;
localparam integer ADC_SAMPLE_WIDTH        = 24;
localparam integer READ_DATA_WIDTH         = 32;

// ADS1247 command
localparam [7:0]  CMD_RDATA     = 8'h12;
localparam [7:0]  CMD_RDATAC    = 8'h14;
localparam [7:0]  CMD_NOP       = 8'hFF;
localparam [7:0]  CMD_RREG_BASE = 8'h20;
localparam [7:0]  CMD_WREG_BASE = 8'h40;
localparam [23:0] CMD_NOP24     = 24'hFF_FF_FF;

// ADS1247 register addresses and unchanged configuration data.
localparam [3:0] ADDR_MUX0    = 4'h0;
localparam [3:0] ADDR_VBIAS   = 4'h1;
localparam [3:0] ADDR_MUX1    = 4'h2;
localparam [3:0] ADDR_SYS0    = 4'h3;
localparam [3:0] ADDR_IDAC0   = 4'hA;
localparam [3:0] ADDR_IDAC1   = 4'hB;
localparam [3:0] ADDR_GPIOCFG = 4'hC;
localparam [3:0] ADDR_GPIODIR = 4'hD;
localparam [3:0] ADDR_GPIODAT = 4'hE;

localparam [7:0] DATA_MUX0    = 8'h01; // AINP=AIN0, AINN=AIN1, burnout current enabled per old config
localparam [7:0] DATA_VBIAS   = 8'h00;
localparam [7:0] DATA_MUX1    = 8'h20; // internal reference on per old config
localparam [7:0] DATA_SYS0    = 8'h20; // PGA/data-rate per old config
localparam [7:0] DATA_IDAC0   = 8'h02;
localparam [7:0] DATA_IDAC1   = 8'h32;
localparam [7:0] DATA_GPIOCFG = 8'h00;
localparam [7:0] DATA_GPIODIR = 8'h00;
localparam [7:0] DATA_GPIODAT = 8'h00;

localparam integer INIT_NUM = 9;

// Main FSM states
localparam [3:0] M_RESET      = 4'd0;
localparam [3:0] M_INIT_START = 4'd1;
localparam [3:0] M_INIT_WAIT  = 4'd2;
localparam [3:0] M_WAIT_DRDY  = 4'd3;
localparam [3:0] M_READ_START    = 4'd4;
localparam [3:0] M_READ_WAIT     = 4'd5;
localparam [3:0] M_RDATAC_START  = 4'd6;
localparam [3:0] M_RDATAC_WAIT   = 4'd7;
localparam [3:0] M_VERIFY_START  = 4'd8;
localparam [3:0] M_VERIFY_WAIT   = 4'd9;

// SPI engine states
localparam [2:0] S_IDLE     = 3'd0;
localparam [2:0] S_CS_SETUP = 3'd1;
localparam [2:0] S_SHIFT    = 3'd2;
localparam [2:0] S_CS_HOLD  = 3'd3;
localparam [2:0] S_DONE     = 3'd4;

// ============================================================
// Registers / wires
// ============================================================

reg [3:0]  r_main_state       /* synthesis PAP_MARK_DEBUG = "1" */;
reg [3:0]  r_init_idx         /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_reset_cnt        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_timeout_cnt      /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_readback     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_expected     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_compare_mask /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_reg_verify_pass  /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_reg_verify_fail  /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_verify_fail_cnt /* synthesis PAP_MARK_DEBUG = "1" */;
reg [3:0]  r_fail_idx         /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_fail_expected    /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_fail_readback    /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_fail_rx_shift    /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_fail_tx_data     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_b3        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_b2        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_b1        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_b0        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_shift_l1  /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]  r_reg_rx_shift_r1  /* synthesis PAP_MARK_DEBUG = "1" */;

reg [2:0]  r_drdy_sync        /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_drdy_pending     /* synthesis PAP_MARK_DEBUG = "1" */;

reg        r_spi_start        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_spi_tx_data      /* synthesis PAP_MARK_DEBUG = "1" */;
reg [5:0]  r_spi_bit_len      /* synthesis PAP_MARK_DEBUG = "1" */;

reg [2:0]  r_spi_state        /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_spi_tx_shift     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_spi_rx_shift     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [5:0]  r_spi_bit_cnt      /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_spi_half_cnt     /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0] r_spi_cs_cnt       /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_spi_done         /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_adc_sclk         /* synthesis PAP_MARK_DEBUG = "1" */;
reg        r_spi_tx_advance   /* synthesis PAP_MARK_DEBUG = "1" */;

reg signed [ADC_SAMPLE_WIDTH-1:0] r_adc_sample     /* synthesis PAP_MARK_DEBUG = "1" */;
reg                             r_sample_valid    /* synthesis PAP_MARK_DEBUG = "1" */;
reg [7:0]                       r_discard_cnt     /* synthesis PAP_MARK_DEBUG = "1" */;

reg [7:0]                       r_avg_cnt         /* synthesis PAP_MARK_DEBUG = "1" */;
reg signed [READ_DATA_WIDTH-1:0] r_avg_sum        /* synthesis PAP_MARK_DEBUG = "1" */;
reg signed [READ_DATA_WIDTH-1:0] r_read_data_out  /* synthesis PAP_MARK_DEBUG = "1" */;
reg                             r_avg_done        /* synthesis PAP_MARK_DEBUG = "1" */;

reg                             r_gpio_master_data /* synthesis PAP_MARK_DEBUG = "1" */;
reg [31:0]                      r_gpio_cnt         /* synthesis PAP_MARK_DEBUG = "1" */;

wire                            w_drdy_fall       /* synthesis PAP_MARK_DEBUG = "1" */;
wire                            w_spi_idle        /* synthesis PAP_MARK_DEBUG = "1" */;
wire signed [READ_DATA_WIDTH-1:0] w_adc_sample_ext /* synthesis PAP_MARK_DEBUG = "1" */;

// ============================================================
// Assignments
// ============================================================

assign o_adc_reset        = i_sys_rst_n;
assign o_adc_start        = i_sys_rst_n;
assign o_adc_sclk         = r_adc_sclk;
assign o_adc_sdi          = r_spi_tx_shift[31];
assign o_read_data        = r_read_data_out;
assign o_gpio_master_data = r_gpio_master_data;

assign w_drdy_fall      = r_drdy_sync[2] & ~r_drdy_sync[1];
assign w_spi_idle       = (r_spi_state == S_IDLE);
assign w_adc_sample_ext = {{(READ_DATA_WIDTH-ADC_SAMPLE_WIDTH){r_adc_sample[ADC_SAMPLE_WIDTH-1]}}, r_adc_sample};

// ============================================================
// Init register table
// ============================================================

function [23:0] f_wreg1;
    input [3:0] addr;
    input [7:0] data;
    begin
        // ADS1247 WREG single-register frame: 0100rrrr, 00000000, data.
        f_wreg1 = {CMD_WREG_BASE | {4'b0000, addr}, 8'h00, data};
    end
endfunction

function [23:0] f_rreg1;
    input [3:0] addr;
    begin
        // ADS1247 RREG single-register frame: 0010rrrr, 00000000, NOP.
        f_rreg1 = {CMD_RREG_BASE | {4'b0000, addr}, 8'h00, CMD_NOP};
    end
endfunction

function [3:0] f_init_addr;
    input [3:0] idx;
    begin
        case (idx)
            4'd0: f_init_addr = ADDR_MUX0;
            4'd1: f_init_addr = ADDR_VBIAS;
            4'd2: f_init_addr = ADDR_MUX1;
            4'd3: f_init_addr = ADDR_SYS0;
            4'd4: f_init_addr = ADDR_IDAC0;
            4'd5: f_init_addr = ADDR_IDAC1;
            4'd6: f_init_addr = ADDR_GPIOCFG;
            4'd7: f_init_addr = ADDR_GPIODIR;
            4'd8: f_init_addr = ADDR_GPIODAT;
            default: f_init_addr = 4'h0;
        endcase
    end
endfunction

function [7:0] f_init_data;
    input [3:0] idx;
    begin
        case (idx)
            4'd0: f_init_data = DATA_MUX0;
            4'd1: f_init_data = DATA_VBIAS;
            4'd2: f_init_data = DATA_MUX1;
            4'd3: f_init_data = DATA_SYS0;
            4'd4: f_init_data = DATA_IDAC0;
            4'd5: f_init_data = DATA_IDAC1;
            4'd6: f_init_data = DATA_GPIOCFG;
            4'd7: f_init_data = DATA_GPIODIR;
            4'd8: f_init_data = DATA_GPIODAT;
            default: f_init_data = 8'h00;
        endcase
    end
endfunction

function [7:0] f_init_mask;
    input [3:0] idx;
    begin
        case (idx)
            // MUX1 bit[7] is CLKSTAT, a read-only clock status bit.
            4'd2: f_init_mask = 8'h7F;

            // IDAC0 bit[7:4] is the read-only revision ID. Only DRDY MODE and
            // IMAG[2:0] are compared against the written configuration.
            4'd4: f_init_mask = 8'h0F;

            default: f_init_mask = 8'hFF;
        endcase
    end
endfunction

function [23:0] f_init_word;
    input [3:0] idx;
    begin
        f_init_word = f_wreg1(f_init_addr(idx), f_init_data(idx));
    end
endfunction

// ============================================================
// DRDY synchronizer and event latch
// Only latch falling edge to avoid repeatedly reading the same low-level DRDY.
// ============================================================

always @(posedge i_sys_clk or negedge i_sys_rst_n) begin
    if (!i_sys_rst_n) begin
        r_drdy_sync    <= 3'b111;
        r_drdy_pending <= 1'b0;
    end else begin
        r_drdy_sync <= {r_drdy_sync[1:0], i_adc_drdy};

        if (w_drdy_fall) begin
            r_drdy_pending <= 1'b1;
        end else if ((r_main_state == M_READ_WAIT) && r_spi_done) begin
            r_drdy_pending <= 1'b0;
        end
    end
end

// ============================================================
// Main ADS1247 control FSM
// ============================================================

always @(posedge i_sys_clk or negedge i_sys_rst_n) begin
    if (!i_sys_rst_n) begin
        r_main_state   <= M_RESET;
        r_init_idx     <= 4'd0;
        r_reset_cnt    <= 32'd0;
        r_timeout_cnt  <= 32'd0;
        r_spi_start    <= 1'b0;
        r_spi_tx_data  <= 32'hFFFF_FFFF;
        r_spi_bit_len  <= 6'd24;
        r_adc_sample   <= {ADC_SAMPLE_WIDTH{1'b0}};
        r_sample_valid <= 1'b0;
        r_discard_cnt  <= 8'd0;
        r_reg_readback <= 8'd0;
        r_reg_expected <= 8'd0;
        r_reg_compare_mask <= 8'hFF;
        r_reg_verify_pass <= 1'b0;
        r_reg_verify_fail <= 1'b0;
        r_reg_verify_fail_cnt <= 8'd0;
        r_fail_idx       <= 4'd0;
        r_fail_expected  <= 8'd0;
        r_fail_readback  <= 8'd0;
        r_fail_rx_shift  <= 32'd0;
        r_fail_tx_data   <= 32'd0;
        r_reg_rx_b3      <= 8'd0;
        r_reg_rx_b2      <= 8'd0;
        r_reg_rx_b1      <= 8'd0;
        r_reg_rx_b0      <= 8'd0;
        r_reg_rx_shift_l1 <= 8'd0;
        r_reg_rx_shift_r1 <= 8'd0;
    end else begin
        r_spi_start    <= 1'b0;
        r_sample_valid <= 1'b0;
        r_reg_verify_pass <= 1'b0;
        r_reg_verify_fail <= 1'b0;

        case (r_main_state)
            M_RESET: begin
                r_init_idx    <= 4'd0;
                r_timeout_cnt <= 32'd0;
                r_discard_cnt <= 8'd0;
                r_reg_readback <= 8'd0;
                r_reg_expected <= 8'd0;
                r_reg_compare_mask <= 8'hFF;

                if (r_reset_cnt >= RESET_DELAY_CYCLES_EFF - 1) begin
                    r_reset_cnt  <= 32'd0;
                    r_main_state <= M_INIT_START;
                end else begin
                    r_reset_cnt  <= r_reset_cnt + 1'b1;
                    r_main_state <= M_RESET;
                end
            end

            M_INIT_START: begin
                r_reset_cnt   <= 32'd0;
                r_timeout_cnt <= 32'd0;

                if (w_spi_idle) begin
                    // For 24-bit transfer, valid TX bits are aligned to [31:8],
                    // because o_adc_sdi sends r_spi_tx_shift[31] first.
                    r_spi_tx_data <= {f_init_word(r_init_idx), 8'h00};
                    r_spi_bit_len <= 6'd24;
                    r_spi_start   <= 1'b1;
                    r_reg_expected <= f_init_data(r_init_idx);
                    r_reg_compare_mask <= f_init_mask(r_init_idx);
                    r_main_state  <= M_INIT_WAIT;
                end
            end

            M_INIT_WAIT: begin
                if (r_spi_done) begin
                    r_main_state <= M_VERIFY_START;
                end
            end

            M_VERIFY_START: begin
                if (w_spi_idle) begin
                    // RREG command/count are followed by two NOP bytes.
                    // The register value is captured from the first NOP byte; the
                    // second NOP gives extra DOUT timing margin on the board.
                    r_spi_tx_data <= {CMD_RREG_BASE | {4'b0000, f_init_addr(r_init_idx)}, 8'h00, CMD_NOP, CMD_NOP};
                    r_spi_bit_len <= 6'd32;
                    r_spi_start   <= 1'b1;
                    r_main_state  <= M_VERIFY_WAIT;
                end
            end

            M_VERIFY_WAIT: begin
                if (r_spi_done) begin
                    r_reg_readback <= r_spi_rx_shift[15:8];
                    r_reg_rx_b3 <= r_spi_rx_shift[31:24];
                    r_reg_rx_b2 <= r_spi_rx_shift[23:16];
                    r_reg_rx_b1 <= r_spi_rx_shift[15:8];
                    r_reg_rx_b0 <= r_spi_rx_shift[7:0];
                    r_reg_rx_shift_l1 <= r_spi_rx_shift[14:7];
                    r_reg_rx_shift_r1 <= r_spi_rx_shift[16:9];

                    if ((r_spi_rx_shift[15:8] & r_reg_compare_mask) == (r_reg_expected & r_reg_compare_mask)) begin
                        r_reg_verify_pass <= 1'b1;

                    if (r_init_idx == INIT_NUM - 1) begin
                        r_init_idx    <= 4'd0;
                        r_timeout_cnt <= 32'd0;
                        r_main_state  <= M_RDATAC_START;
                    end else begin
                        r_init_idx    <= r_init_idx + 1'b1;
                        r_main_state  <= M_INIT_START;
                    end
                    end else begin
                        r_reg_verify_fail     <= 1'b1;
                        r_reg_verify_fail_cnt <= r_reg_verify_fail_cnt + 1'b1;
                        r_fail_idx            <= r_init_idx;
                        r_fail_expected       <= r_reg_expected;
                        r_fail_readback       <= r_spi_rx_shift[15:8];
                        r_fail_rx_shift       <= r_spi_rx_shift;
                        r_fail_tx_data        <= r_spi_tx_data;
                        r_init_idx            <= 4'd0;
                        r_timeout_cnt         <= 32'd0;
                        r_main_state          <= M_INIT_START;
                    end
                end
            end

            M_RDATAC_START: begin
                // Enter ADS1247 continuous read mode once after all register writes.
                // 8-bit command is aligned to [31:24] because o_adc_sdi sends bit[31] first.
                if (w_spi_idle) begin
                    r_spi_tx_data <= {CMD_RDATAC, 24'h00_00_00};
                    r_spi_bit_len <= 6'd8;
                    r_spi_start   <= 1'b1;
                    r_main_state  <= M_RDATAC_WAIT;
                end
            end

            M_RDATAC_WAIT: begin
                if (r_spi_done) begin
                    r_timeout_cnt <= 32'd0;
                    r_main_state  <= M_WAIT_DRDY;
                end
            end

            M_WAIT_DRDY: begin
                if (r_timeout_cnt < ADC_TIMEOUT_CYCLES_EFF) begin
                    r_timeout_cnt <= r_timeout_cnt + 1'b1;
                end

                if (r_timeout_cnt >= ADC_TIMEOUT_CYCLES_EFF) begin
                    r_timeout_cnt <= 32'd0;
                    r_main_state  <= M_RESET;
                end else if (r_drdy_pending) begin
                    r_main_state  <= M_READ_START;
                end
            end

            M_READ_START: begin
                if (w_spi_idle) begin
                    // RDATAC mode: after DRDY, directly clock out 24 conversion bits.
                    // No RDATA command is sent here.
                    r_spi_tx_data <= {CMD_NOP24, 8'h00};
                    r_spi_bit_len <= 6'd24;
                    r_spi_start   <= 1'b1;
                    r_main_state  <= M_READ_WAIT;
                end
            end

            M_READ_WAIT: begin
                if (r_spi_done) begin
                    r_adc_sample <= r_spi_rx_shift[ADC_SAMPLE_WIDTH-1:0];

                    if (r_discard_cnt < DISCARD_NUM_EFF) begin
                        r_discard_cnt  <= r_discard_cnt + 1'b1;
                        r_sample_valid <= 1'b0;
                    end else begin
                        r_sample_valid <= 1'b1;
                    end

                    r_timeout_cnt <= 32'd0;
                    r_main_state  <= M_WAIT_DRDY;
                end
            end

            default: begin
                r_main_state <= M_RESET;
            end
        endcase
    end
end

// ============================================================
// SPI engine
// ============================================================

always @(posedge i_sys_clk or negedge i_sys_rst_n) begin
    if (!i_sys_rst_n) begin
        r_spi_state        <= S_IDLE;
        r_spi_tx_shift     <= 32'hFFFF_FFFF;
        r_spi_rx_shift     <= 32'd0;
        r_spi_bit_cnt      <= 6'd0;
        r_spi_half_cnt     <= 32'd0;
        r_spi_cs_cnt       <= 32'd0;
        r_spi_done         <= 1'b0;
        r_adc_sclk         <= 1'b0;
        r_spi_tx_advance   <= 1'b0;
        o_adc_cs_n         <= 1'b1;
    end else begin
        r_spi_done <= 1'b0;

        case (r_spi_state)
            S_IDLE: begin
                r_adc_sclk         <= 1'b0;
                o_adc_cs_n         <= 1'b1;
                r_spi_half_cnt     <= 32'd0;
                r_spi_cs_cnt       <= 32'd0;
                r_spi_bit_cnt      <= 6'd0;
                r_spi_tx_advance   <= 1'b0;
                if (r_spi_start) begin
                    r_spi_tx_shift <= r_spi_tx_data;
                    r_spi_rx_shift <= 32'd0;
                    o_adc_cs_n     <= 1'b0;
                    r_spi_state    <= S_CS_SETUP;
                end
            end

            S_CS_SETUP: begin
                r_adc_sclk <= 1'b0;
                o_adc_cs_n <= 1'b0;

                if (r_spi_cs_cnt >= CS_DELAY_CYCLES_EFF - 1) begin
                    r_spi_cs_cnt <= 32'd0;
                    r_spi_state  <= S_SHIFT;
                end else begin
                    r_spi_cs_cnt <= r_spi_cs_cnt + 1'b1;
                end
            end

            S_SHIFT: begin
                o_adc_cs_n <= 1'b0;

                if (r_spi_half_cnt >= SCLK_HALF_PERIOD_CYCLES - 1) begin
                    r_spi_half_cnt <= 32'd0;

                    if (r_adc_sclk == 1'b0) begin
                        // Rising edge: prepare the next DIN bit after the
                        // previous falling-edge sample has completed. The first
                        // bit is already stable from CS setup, so it is not
                        // advanced before the first falling edge.
                        r_adc_sclk <= 1'b1;
                        if (r_spi_tx_advance) begin
                            r_spi_tx_shift   <= {r_spi_tx_shift[30:0], 1'b0};
                            r_spi_tx_advance <= 1'b0;
                        end
                    end else begin
                        // Falling edge: ADS1247 latches DIN here and updates
                        // DOUT on rising edges, so sample SDO here.
                        r_adc_sclk     <= 1'b0;
                        r_spi_rx_shift <= {r_spi_rx_shift[30:0], i_adc_sdo};

                        if (r_spi_bit_cnt == r_spi_bit_len - 1) begin
                            r_spi_bit_cnt <= 6'd0;
                            r_spi_tx_advance <= 1'b0;
                            r_spi_state   <= S_CS_HOLD;
                        end else begin
                            r_spi_bit_cnt <= r_spi_bit_cnt + 1'b1;
                            r_spi_tx_advance <= 1'b1;
                        end
                    end
                end else begin
                    r_spi_half_cnt <= r_spi_half_cnt + 1'b1;
                end
            end

            S_CS_HOLD: begin
                r_adc_sclk <= 1'b0;
                o_adc_cs_n <= 1'b0;

                if (r_spi_cs_cnt >= CS_DELAY_CYCLES_EFF - 1) begin
                    r_spi_cs_cnt <= 32'd0;
                    r_spi_state  <= S_DONE;
                end else begin
                    r_spi_cs_cnt <= r_spi_cs_cnt + 1'b1;
                end
            end

            S_DONE: begin
                r_adc_sclk  <= 1'b0;
                o_adc_cs_n  <= 1'b1;
                r_spi_done  <= 1'b1;
                r_spi_state <= S_IDLE;
            end

            default: begin
                r_spi_state <= S_IDLE;
            end
        endcase
    end
end

// ============================================================
// Signed sample-sum calculation
// ============================================================

always @(posedge i_sys_clk or negedge i_sys_rst_n) begin
    if (!i_sys_rst_n) begin
        r_avg_cnt       <= 8'd0;
        r_avg_sum       <= 'sd0;
        r_read_data_out <= {READ_DATA_WIDTH{1'b0}};
        r_avg_done      <= 1'b0;
    end else begin
        r_avg_done <= 1'b0;

        if (r_sample_valid) begin
            if (r_avg_cnt == AVG_NUM_EFF - 1) begin
                r_read_data_out <= (r_avg_sum + w_adc_sample_ext);
                r_avg_sum       <= 'sd0;
                r_avg_cnt       <= 8'd0;
                r_avg_done      <= 1'b1;
            end else begin
                r_avg_sum <= r_avg_sum + w_adc_sample_ext;
                r_avg_cnt <= r_avg_cnt + 1'b1;
            end
        end
    end
end

// ============================================================
// GPIO master pulse when sample-sum data is updated
// ============================================================

always @(posedge i_sys_clk or negedge i_sys_rst_n) begin
    if (!i_sys_rst_n) begin
        r_gpio_master_data <= 1'b0;
        r_gpio_cnt         <= 32'd0;
    end else begin
        if (r_avg_done) begin
            r_gpio_master_data <= 1'b1;
            r_gpio_cnt         <= GPIO_PULSE_CYCLES_EFF - 1;
        end else if (r_gpio_cnt != 32'd0) begin
            r_gpio_cnt         <= r_gpio_cnt - 1'b1;
            r_gpio_master_data <= 1'b1;
        end else begin
            r_gpio_master_data <= 1'b0;
        end
    end
end

endmodule
